# Generated by Django 3.0.5 on 2021-06-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
