# Generated by Django 3.0.5 on 2021-06-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_ordermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
